name: Publish GrapesJS Core
on:
  push:
    branches: [dev]
    paths:
      - 'packages/core/**'

jobs:
  publish:
    if: "contains(github.event.head_commit.message, 'Release GrapesJS core:')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
      - name: Publish Core
        run: pnpm publish --access public
        working-directory: ./packages/core
